# NumPy array and basics

In [6]:
import numpy as np
import random

In [3]:
arr_1d = np.array([1,2,3,4,5]) 
print("1D array: \n",arr_1d)

arr_2d = np.array([[1,3,2],[7,5,6]]) 
print("2D array: \n",arr_2d)

1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 3 2]
 [7 5 6]]


## Numpy vs list

In [10]:
py_list = [1,3,45,6,7]
print("Multiplication :",py_list*2)

n_array = np.array([1,3,45,6,7]) #it outputs elements wise multiplication
print("Multiplication :",n_array*2)

Multiplication : [1, 3, 45, 6, 7, 1, 3, 45, 6, 7]
Multiplication : [ 2  6 90 12 14]


## creating array from scratch

In [17]:
zeros = np.zeros((3,3))
print("Zeros Array:\n",zeros)

ones = np.ones((3,3))
print("Ones Array:\n",ones)

full = np.full((3,3),6)
print("Full Array:\n",full)

rand = np.random.random((2,4))
print("Random Array:\n",rand)

squence = np.arange(0,12,3)
print("Squence Array:\n",squence)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random Array:
 [[2.50072613e-01 5.29851622e-04 8.83872330e-02 1.16053077e-01]
 [6.33625923e-01 1.94733192e-01 6.26380423e-01 4.94324143e-01]]
Squence Array:
 [0 3 6 9]


## Vector,Matrix and Tensor

In [20]:
vector = np.array([1,2,3])
print("vector: \n",vector)

Matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: \n",Matrix)

tensor = np.array([[[1,2],[2,3]],
                   [[4,5],[5,7]]])
print("tensor: \n",tensor)

vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [2 3]]

 [[4 5]
  [5 7]]]


## ARRAY properties

In [25]:
arr = np.array([[1,2,2]
                ,[3,3,4]])
print("Shape: \n",arr.shape)
print("Dimension: \n",arr.ndim)
print("DataType: \n",arr.dtype)
print("Size: \n",arr.size)

Shape: 
 (2, 3)
Dimension: 
 2
DataType: 
 int64
Size: 
 6


### Array Reshape

In [40]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape((3,4))
print("Reshape: \n",reshaped)

flattend = reshaped.flatten()
print("flatten: \n",flattend)

raveled = reshaped.ravel 
print("Ravel: \n",ravel)

#flatten() returns a copy (safe, no change to original), while ravel() returns a view if possible (faster, may affect original).
print (reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel: 
 <built-in method ravel of numpy.ndarray object at 0x00000244BAAF1650>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
