## NumPy Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(12)
print(arr)
print ("Basic Slicing: ",arr[2:5])
print("With Step: ",arr[1:8:2])
print("Negative Indexing: ",arr[-3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Basic Slicing:  [2 3 4]
With Step:  [1 3 5 7]
Negative Indexing:  9


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element: ", arr_2d[1, 1])
print("Entire Row: ", arr_2d[1])
print("Entire Coloumn: ", arr_2d[:, 1])

Specific Element:  5
Entire Row:  [4 5 6]
Entire Coloumn:  [2 5 8]


### Sorting

In [5]:
Unsorted = np.array([3,5,78,9,1,11,23,2,4,0])
print("Sorted Array: ",np.sort(Unsorted))

unsorted_2d_array = np.array([[2,3],[1,1],[0,45]])
print("Sorted 2DArray column wise: ",np.sort(unsorted_2d_array, axis=0))

Sorted Array:  [ 0  1  2  3  4  5  9 11 23 78]
Sorted 2DArray column wise:  [[ 0  1]
 [ 1  3]
 [ 2 45]]


###  Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ",even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### Filter with mask

In [7]:
mask = numbers > 5
print ("greater than 5: ",numbers [mask])
print(numbers)

greater than 5:  [ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Fancy Indexing vs np.where()

In [8]:
indices = [0,3,5]
print("Indexing: ",numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print ("NP Where ",numbers[where_result])

Indexing:  [1 4 6]
(array([5, 6, 7, 8, 9]),)
NP Where  [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5,numbers * 2, numbers) #agar numbers 5 se bara hoga then woh number 2 se multiply hojayega.
print(condition_array)

condition_array = np.where(numbers > 5, True , False )
print(condition_array)


[ 1  2  3  4  5 12 14 16 18 20]
[False False False False False  True  True  True  True  True]


### Adding and Removing

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility 

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6,])
c = np.array([7,8,9])

print("Compatibility: ", a.shape == b.shape)

Compatibility:  True


In [18]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)
print(original)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
[[1 2]
 [3 4]]


In [24]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr,3)
print("array after deletion: ",deleted)


array after deletion:  [1 2 3 5 6 7]
