## Advance operations with business example

In [2]:
import numpy as np

In [3]:
# Data Structure: {restuarant_id, 2021, 2022, 2023, 2024}
sales_data =np.array ([
#   {id, 2021,  2022,   2023,    2024}
    [1, 150000, 180000, 220000, 50000], #Paradise biryani
    [2, 120000, 140000, 160000, 190000], #beijin bites 
    [3, 200000, 230000, 260000, 300000], #pizza hub
    [4, 180000, 210000, 240000, 270000], #burger lab
    [5, 160000, 185000, 205000, 440000], #chai point
    
])

print("="*10,"Zomato Analysis","="*10)
print("sales data shape: ",sales_data.shape)
print("sample data for first 3 restuarants:\n" ,sales_data[:3,1:])

========== Zomato Analysis ==========
sales data shape:  (5, 5)
sample data for first 3 restuarants:
 [[150000 180000 220000  50000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]]


In [4]:
#total sales per year

print(np.sum(sales_data,axis=0))
"""sum (total top to bottom) i.e coloumn wise one by one like first sum total of 
year 2021 then 2022 then 2023 then 2024"""

#other method
yearly_total = np.sum(sales_data[:,1:], axis=0)
print(yearly_total)

[     15  810000  945000 1085000 1250000]
[ 810000  945000 1085000 1250000]


In [5]:
#minimum sales per restuarant?
#minimum sales per year ?

#maximum sales per year ?
#maximum sales per restuarant?

#1.A
min_sales_per_rt =sales_data[:,1:].min(axis = 1) #checks the data left to right of all restuarant and gives the min value
print(min_sales_per_rt)

#1.B
min_sales_per_year =sales_data[:,1:].min(axis = 0) #checks the data top to bottom that among 5 restuarant which have the minimum sales in each year
print(min_sales_per_year)

#2.A
max_sales_per_year =sales_data[:,1:].max(axis = 0) #checks the data top to bottom and find the max sales among all years 
print(max_sales_per_year)

#2.B

max_sales_per_rt =sales_data[:,1:].max(axis = 1) #checks the data left to right k kis restuarant ne kis saal mein subse ziada kamaya tha
print(max_sales_per_rt)




[ 50000 120000 200000 180000 160000]
[120000 140000 160000  50000]
[200000 230000 260000 440000]
[220000 190000 300000 270000 440000]


In [6]:
#Average Sales per Restuarat
average_sales_per_restuarant = sales_data[:,1:].mean(axis = 1) 
# calculate restuarant ka 4 saal ka average like left to right thats why we put axis =1
print(average_sales_per_restuarant)

#average of chai point
average_chaipoint = sales_data[4,1:].mean()
print(average_chaipoint)


[150000. 152500. 247500. 225000. 247500.]
247500.0


In [7]:
#cumsum = Cumulative Sum.

# Get running total of all restaurant sales from 2021 to 2024 (excluding IDs)
cumsum_sales = sales_data[:,1:].cumsum(axis=1)
print(cumsum_sales) 

[[150000 330000 550000 600000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 990000]]


In [11]:
#vectorize operations

vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])
print(vector1 + vector2)
print(vector1 * vector2)
print(np.dot(vector1,vector2))

[ 7  9 11 13 15]
[ 6 14 24 36 50]
130


In [18]:
restuarant = np.array(["chai","coffee","milkshake","burger","pizza","tikka"])
vectorized_upper = (np.vectorize(str.upper))
print(vectorized_upper(restuarant))
print(restuarant)


['CHAI' 'COFFEE' 'MILKSHAKE' 'BURGER' 'PIZZA' 'TIKKA']
['chai' 'coffee' 'milkshake' 'burger' 'pizza' 'tikka']


### Broadcasting

In [21]:
monthly_avg = sales_data[:,1:] / 12
print(monthly_avg)

[[12500.         15000.         18333.33333333  4166.66666667]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 36666.66666667]]
